services:
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    env_file:
      - ./fastapi/.env
    depends_on:
      - mongo
      - redis
    container_name: fastapi_app
  
  telebot:
    build:
      context: ./telebot
      dockerfile: Dockerfile
    env_file:
      - ./telebot/.env
    depends_on:
      - mongo
    container_name: telebot_app

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "127.0.0.1:6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "127.0.0.1:9090:9090"
    deploy:
      resources:
        limits:
          memory: 150M

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9100:9100"
  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys
      - /var/lib/docker:/var/lib/docker
    deploy:
      resources:
        limits:
          memory: 200M


  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi
      - telebot

volumes:
  mongodb_data:
  redis_data:
  grafana_data:
