services:
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    env_file:
      - ./fastapi/.env
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - mongo
      - redis
    networks:
      - internal_network
    environment:
      - LOGS_FILE_PATH=/app/logs/fastapi.log
      - LOG_LEVEL=info
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
  
  telebot:
    build:
      context: ./telebot
      dockerfile: Dockerfile
    env_file:
      - ./telebot/.env
    depends_on:
      - mongo
    container_name: telebot_app
    networks:
      - internal_network

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - internal_network
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "127.0.0.1:6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - internal_network
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "127.0.0.1:9090:9090"
    deploy:
      resources:
        limits:
          memory: 150M
    networks:
      - internal_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - internal_network
  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    networks:
      - internal_network
    expose:
      - 9100
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys
      - /var/lib/docker:/var/lib/docker
      - /sys/fs/cgroup:/sys/fs/cgroup
    deploy:
      resources:
        limits:
          memory: 200M
    networks:
      - internal_network


  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./black_ips.conf:/etc/nginx/black_ips.conf
    depends_on:
      - fastapi
      - telebot
    networks:
      - internal_network
      - external_network

networks:
  internal_network:
    driver: bridge
  external_network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  grafana_data:
