global:
  scrape_interval: 60s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapi:5000']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  # - job_name: 'mongodb'
  #   static_configs:
  #     - targets: ['mongo:27017']
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis:6379']
  # - job_name: 'telebot'
  #   static_configs:
  #     - targets: ['telebot']