name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH to VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/mayntu/arizonaPlugin
            git pull origin main
            echo "Updating FastAPI service..."
            docker compose up -d --build fastapi
            echo "Waiting for FastAPI replicas to be ready..."
            echo "Waiting for FastAPI replicas to be ready..."
            for i in {1..30}; do
                if curl -s -o /dev/null -w "%{http_code}" http://localhost:5000 | grep -q "200"; then
                    echo "FastAPI is ready!"
                    break
                else
                    echo "Waiting for FastAPI..."
                    sleep 5
                fi
            done

            echo "Restarting other services..."
            docker compose up -d --build nginx mongo redis prometheus grafana telebot cadvisor node_exporter

            echo "Deployment completed."

